### ISSUE TITLE
hermes(penumbra): update trusting period to use `unbonding_delay`

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/hermes#13]
> After we merge https://github.com/penumbra-zone/penumbra/issues/3738 (this sprint), we should make a note to update the trusting period calculation to take `StakeParameters::unbonding_delay` instead of being epoch based. 

https://github.com/penumbra-zone/hermes/commit/039a9f281e26ec7c591c347def5ca553e3f0496e#r138910753

**Comment by zbuc** [comment]
This has been completed.
